


TYPE=Ethernet
BOOTPROTO=static
IPADDR=192.168.56.101
DEFROUTE=yes
PEERDNS=yes
PEERROUTES=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens33
UUID=a764069e-3b7a-428d-98ae-b71e27430f13
DEVICE=ens33
ONBOOT=yes




ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.67.189  netmask 255.255.255.0  broadcast 172.16.67.255
        inet6 fe80::3a1e:6388:7ed4:8acc  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:1f:dd:88  txqueuelen 1000  (Ethernet)
        RX packets 336  bytes 30733 (30.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 213  bytes 40131 (39.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens37: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:0c:29:1f:dd:92  txqueuelen 1000  (Ethernet)
        RX packets 7  bytes 832 (832.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 68  bytes 5784 (5.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 68  bytes 5784 (5.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0






/etc/resolv.conf


sshpass -p oracle ssh -X root@192.168.25.101


sshpass -p oracle ssh -X root@192.168.25.101

ssh -X oracle@192.168.25.101




vi /etc/sysconfig/network-scripts/ifcfg-eth1

DEVICE=eth1
BOOTPROTO=static
ONBOOT=yes
IPADDR=192.168.25.101








cat <<EOF> /etc/resolv.conf
# Generated by NetworkManager
search localdomain
nameserver 127.0.0.1
EOF


sysctl kernel.hostname=ol7-122-rac1.localdomain



cat <<EOF>/etc/sysconfig/network
NETWORKING=yes
NETWORKING_IPV6=yes
HOSTNAME=ol7-122-rac1.localdomain
EOF

- ---------------------------------------
- Editar os drivers de rede
- ---------------------------------------

cat <<EOF> /etc/sysconfig/network-scripts/ifcfg-ens33
DHCP_HOSTNAME=ol7-122-rac1.localdomain
BOOTPROTO=static
IPADDR=192.168.25.101
NETWORK=192.0.0.0
NETMASK=255.0.0.0
TYPE=Ethernet
DEFROUTE=yes
PEERDNS=yes
PEERROUTES=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens33
UUID=991f583a-5851-4411-b889-5d994896ae3b
DEVICE=ens33
ONBOOT=yes
EOF


cat <<EOF> /etc/sysconfig/network-scripts/ifcfg-ens34
BOOTPROTO=static
IPADDR=192.168.1.101
NETWORK=192.0.0.0
NETMASK=255.0.0.0
DHCP_HOSTNAME=ol7-122-rac1.localdomain
TYPE=Ethernet
DEFROUTE=yes
PEERDNS=yes
PEERROUTES=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens34
UUID=1f21f76c-8e94-435a-a4be-512fcc0491e8
DEVICE=ens34
ONBOOT=yes
EOF




cat <<EOF> /etc/sysconfig/network-scripts/ifcfg-ens39
BOOTPROTO=dhcp
DHCP_HOSTNAME=ol7-122-rac1.localdomain
TYPE=Ethernet
DEFROUTE=yes
PEERDNS=yes
PEERROUTES=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens39
DEVICE=ens39
ONBOOT=yes
EOF



- ---------------------------------------------------------------
- Logo apos de fazer as alterações, reinicie os serviços da REDE
- ---------------------------------------------------------------

service network restart

- ---------------------------------------------------------------
- Ajustar /etc/hosts
- ---------------------------------------------------------------

cat <<EOF> /etc/hosts
# 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
# ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

127.0.0.1       localhost.localdomain   localhost

# Public
192.168.25.101   ol7-122-rac1.localdomain        ol7-122-rac1
192.168.25.102   ol7-122-rac2.localdomain        ol7-122-rac2

# Private
192.168.1.101   ol7-122-rac1-priv.localdomain   ol7-122-rac1-priv
192.168.1.102   ol7-122-rac2-priv.localdomain   ol7-122-rac2-priv

# Virtual
192.168.25.103   ol7-122-rac1-vip.localdomain    ol7-122-rac1-vip
192.168.25.104   ol7-122-rac2-vip.localdomain    ol7-122-rac2-vip

# SCAN
192.168.25.105   ol7-122-scan.localdomain ol7-122-scan
192.168.25.106   ol7-122-scan.localdomain ol7-122-scan
192.168.25.107   ol7-122-scan.localdomain ol7-122-scan
EOF





192.168.25.101   ol7-122-rac1.localdomain        ol7-122-rac1





ssh oracle@172.16.67.191


export SOFTWARE_LOCATION=/tmp
cd /u01/app/12.2.0.1/grid
unzip -qv $SOFTWARE_LOCATION/Grid12c.zip




