

[root@srvoraprod ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0
ONBOOT=yes
NM_CONTROLLED=yes
BOOTPROTO=static
BROADCAST=129.1.255.255
IPADDR=129.1.7.250
NETWORK=129.1.0.0
NETMASK=255.255.0.0
GATEWAY=129.1.100.254




[root@srvoraprod ~]# cat /etc/resolv.conf
# Generated by NetworkManager
search caltabiano.net.br



scp /home/oracle/.ssh/id_rsa.pub oracle@srvorastandby:/home/oracle/.ssh/authorized_keys









NAO INSTALAR O S.O COM KERNEL ------------------------>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   UEK



[root@srvoraprod ~]# cat /etc/grub.conf
# grub.conf generated by anaconda
#
# Note that you do not have to rerun grub after making changes to this file
# NOTICE:  You have a /boot partition.  This means that
#          all kernel and initrd paths are relative to /boot/, eg.
#          root (hd0,1)
#          kernel /vmlinuz-version ro root=/dev/sda3
#          initrd /initrd-[generic-]version.img
#boot=/dev/sda
default=1
timeout=5
splashimage=(hd0,1)/grub/splash.xpm.gz
hiddenmenu
title Oracle Linux Server Unbreakable Enterprise Kernel (3.8.13-68.3.2.el6uek.x86_64)
        root (hd0,1)
        kernel /vmlinuz-3.8.13-68.3.2.el6uek.x86_64 ro root=UUID=8bd29f3e-df16-47a4-b452-fa0f8ba6cd72 rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=br-abnt2 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_NO_LVM rd_NO_DM LANG=en_US.UTF-8 rhgb quiet numa=off transparent_hugepage=never
        initrd /initramfs-3.8.13-68.3.2.el6uek.x86_64.img
title Oracle Linux Server Red Hat Compatible Kernel (2.6.32-504.23.4.el6.x86_64)
        root (hd0,1)
        kernel /vmlinuz-2.6.32-504.23.4.el6.x86_64 ro root=UUID=8bd29f3e-df16-47a4-b452-fa0f8ba6cd72 rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=br-abnt2 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_NO_LVM rd_NO_DM LANG=en_US.UTF-8 rhgb quiet numa=off transparent_hugepage=never
        initrd /initramfs-2.6.32-504.23.4.el6.x86_64.img
title Oracle Linux Server Red Hat Compatible Kernel (2.6.32-504.el6.x86_64)
        root (hd0,1)
        kernel /vmlinuz-2.6.32-504.el6.x86_64 ro root=UUID=8bd29f3e-df16-47a4-b452-fa0f8ba6cd72 rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=br-abnt2 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_NO_LVM rd_NO_DM LANG=en_US.UTF-8 rhgb quiet numa=off transparent_hugepage=never
        initrd /initramfs-2.6.32-504.el6.x86_64.img




[root@srvorastandby ________________ [] ~]# shutdown -r now



[root@srvorastandby ________________ [] ~]# uname -r
2.6.32-504.23.4.el6.x86_64


======================================================================================================================================
cd /media/RHEL.../Server

	rpm -Uvh yum-download*
	rpm -Uvh yum-utils*

cd /etc/yum.repos.d

wget http://public-yum.oracle.com/public-yum-ol6.repo

mv public-yum-ol6.repo public-yum-ol6.repo.old
mv public-yum-ol6.repo.1 public-yum-ol6.repo


# yum install oracle-rdbms-server-11gR2-preinstall

yum install -y oracle-rdbms-server-11gR2-preinstall --nogpgcheck

# yum search -y oracleasm
yum install kmod-oracleasm.x86_64 -y --nogpgcheck
yum install oracleasm-support.x86_64 -y --nogpgcheck

yum update -y --nogpgcheck

#oracleasm-support-2.1.8-1.el6.x86_64.rpm
======================================================================================================================================

/etc/init.d/iptables status

find /etc/selinux/config -exec sed -i 's/SELINUX=/#SELINUX=/g'  {} \;
echo "SELINUX=disabled" >> /etc/selinux/config

/etc/init.d/iptables stop
chkconfig iptables off

======================================================================================================================================


echo -e "oracle\noracle" | passwd oracle

id oracle



======================================================================================================================================



oracleasm configure -i

oracleasm init


cd /u02/grid/rpm/

rpm -ivh cvuqdisk-1.0.9-1.rpm

ll  /sys/kernel/mm/redhat_transparent_hugepage


oracleasm createdisk DISK1 /dev/sda3
oracleasm createdisk DISK2 /dev/sda5
oracleasm createdisk DISK3 /dev/sda6
oracleasm createdisk DISK4 /dev/sda7
oracleasm createdisk DISK5 /dev/sda9



======================================================================================================================================

# Do not remove the following line, or various programs
# that require network functionality will fail.
#::1            localhost6.localdomain6 localhost6

127.0.0.1         localhost.localdomain   localhost
192.168.116.134   jbhomolog.com.br        jbhomolog






# Do not remove the following line, or various programs
# that require network functionality will fail.
#::1            localhost6.localdomain6 localhost6

127.0.0.1       localhost.localdomain   localhost

129.1.6.250     srvorahomolog.caltabiano.net.br srvorahomolog
129.1.7.250     srvorastandby.caltabiano.net.br srvorastandby
129.1.2.250     srvoraprod.caltabiano.net.br    srvoraprod


======================================================================================================================================

chown -R oracle:oinstall /u01
chown -R oracle:oinstall /u02

chmod -R 755 /u02



======================================================================================================================================

# .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
PATH=$PATH:$HOME/bin:/sbin
export PATH

# Begin Oracle settings
export ORACLE_SID=orcl
export ORACLE_BASE="/u01/app/oracle"
export ORACLE_HOME="$ORACLE_BASE/product/11.2.0/db_1"
export ORACLE_GRID_HOME="/u01/app/11.2.0/grid"
export NLS_LANG="AMERICAN_AMERICA.WE8ISO8859P1"
export NLS_DATE_FORMAT="DD/MM/RRRR hh24:mi"
export LD_LIBRARY_PATH="$ORACLE_HOME/lib:/lib64:/usr/lib64:/usr/X11R6/lib64:."
export THREADS_FLAG="native"
export PATH="$ORACLE_GRID_HOME/bin:$ORACLE_HOME/bin:$ORACLE_HOME/OPatch:$ORACLE_BASE/admin/otlp/scripts:/sbin:$PATH:/usr/X11R6/lib64:/usr/X11R6/bin:."
export SQLPATH="$ORACLE_BASE/admin/scripts/sql"
export PS1="[\u@\h [\$ORACLE_SID] \W]\\$ "

# export PS1="[\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h [\$ORACLE_SID] \[\033[01;33m\]\W\[\033[00m\]]\$ "


umask 022

alias home="cd $ORACLE_HOME"
alias base="cd $ORACLE_BASE"
alias admin="cd $ORACLE_BASE/admin"
alias sql="sqlplus / as sysdba"
alias asm="export ORAENV_ASK=NO ; ORACLE_SID=+ASM ; . oraenv; export ORAENV_ASK=YES"
alias sid="export ORAENV_ASK=NO ; ORACLE_SID=orcl ; . oraenv; export ORAENV_ASK=YES"

# End Oracle settings


======================================================================================================================================

. .bash_profile

mkdir -p $ORACLE_GRID_HOME

mkdir -p $ORACLE_HOME




======================================================================================================================================

mkdir /u02/ora_install

/u02/ora_install/grid/runInstaller

/u02/ora_install/database/runInstaller








================================================= APLICAR PSU ========================================================================


$ORACLE_GRID_HOME/OPatch/ocm/bin/emocmrsp  -no_banner -output /u02/ora_install/ocm_grid.rsp

### Com o usuário root
su -

/u01/app/11.2.0/grid/OPatch/opatch auto /u02/ora_install/patches/20485808 -ocmrf /u02/ora_install/ocm_grid.rsp -oh /u01/app/11.2.0/grid


======================================================================================================================================

 emctl status dbconsole

 emctl stop dbconsole




======================================================================================================================================

$ORACLE_HOME/OPatch/ocm/bin/emocmrsp  -no_banner -output /u02/ora_install/ocm_db.rsp

### Com o usuário root

/u01/app/oracle/product/11.2.0/db_1/OPatch/opatch auto /u02/ora_install/patches/20485808 -ocmrf /u02/ora_install/ocm_db.rsp -oh /u01/app/oracle/product/11.2.0/db_1


======================================================================================================================================


 emctl start dbconsole


======================================================================================================================================

chmod -R 755 $ORACLE_GRID_HOME

chmod -R 755 $ORACLE_HOME


srvctl status diskgroup -g DGDATA

crsctl status resource -t


$ORACLE_GRID_HOME/OPatch/opatch lsinventory -detail -oh $ORACLE_GRID_HOME | grep -i "Patch description\|OUI version\|OPatch version\|Oracle Home"

$ORACLE_GRID_HOME/OPatch/opatch lsinventory -oh $ORACLE_GRID_HOME

