
BEGIN

DBMS_OUTPUT.PUT_LINE('BEGIN');
FOR X IN (SELECT OWNER,TABLE_NAME,TEMPORARY FROM DBA_TABLES WHERE TEMPORARY='Y' AND OWNER='CONSINCO')LOOP
	
	DBMS_OUTPUT.PUT_LINE('DBMS_STATS.DELETE_TABLE_STATS(''' || X.OWNER || ''',''' || X.TABLE_NAME || ''');');
	DBMS_OUTPUT.PUT_LINE('DBMS_STATS.LOCK_TABLE_STATS(''' || X.OWNER || ''','''|| X.TABLE_NAME || ''');');

END LOOP;
DBMS_OUTPUT.PUT_LINE('END;' || CHR(10) || '/');
END;
/