-- -----------------------------------------------------------------------------------
-- Autor           : Johab Benicio de Oliveira.
-- -----------------------------------------------------------------------------------

set serveroutput on
set pages 100 lines 200 long 200

DECLARE
V_NOMBASE VARCHAR2(8) := '&NOME_DA_NOVA_BASE';
V_DIRETORIO VARCHAR2(90):= '&LOCAL_FILE_SYSTEM';
V_TAMANHO_REDO NUMBER(4);
V_MAX_MEMBER VARCHAR2(90);
V_MAX_MEMBER2 VARCHAR2(90);
V_MAX_GROUP NUMBER(3);

V_MEMBER VARCHAR2(90);
V_CONTAGEM_REDO number(2);
V_CONTAGEM_MEMBER NUMBER(2);

BEGIN

	DBMS_OUTPUT.PUT_LINE('	');
	DBMS_OUTPUT.PUT_LINE('	');
	DBMS_OUTPUT.PUT_LINE('RUN{ ');
	DBMS_OUTPUT.PUT_LINE('     ALLOCATE AUXILIARY CHANNEL NEWDB1 DEVICE TYPE DISK;');

		FOR X IN (SELECT  FILE_ID, TABLESPACE_NAME FROM DBA_DATA_FILES order by 1) LOOP
			DBMS_OUTPUT.PUT_LINE('  SET NEWNAME FOR DATAFILE ' || X.FILE_ID || ' TO ''' || V_DIRETORIO || X.TABLESPACE_NAME || X.FILE_ID || '.dbf'';');
		END LOOP;

		FOR X IN (SELECT  FILE_ID, TABLESPACE_NAME FROM DBA_TEMP_FILES order by 1) LOOP
			DBMS_OUTPUT.PUT_LINE('  SET NEWNAME FOR TEMPFILE ' || X.FILE_ID || ' TO ''' || V_DIRETORIO || X.TABLESPACE_NAME || X.FILE_ID || '.dbf'';');
		END LOOP;

		DBMS_OUTPUT.PUT_LINE('  DUPLICATE TARGET DATABASE TO ' || V_NOMBASE);
		DBMS_OUTPUT.PUT_LINE('  LOGFILE');

		SELECT MAX(BYTES)/1024/1024 INTO V_TAMANHO_REDO FROM V$LOG;

		FOR Y1 IN (SELECT DISTINCT GROUP# FROM V$LOGFILE ) LOOP

			SELECT COUNT(MEMBER) INTO V_CONTAGEM_MEMBER FROM V$LOGFILE WHERE GROUP# = Y1.GROUP#;
				IF V_CONTAGEM_MEMBER > 1 THEN

					SELECT MAX(MEMBER) MEMBER INTO V_MAX_MEMBER FROM V$LOGFILE WHERE GROUP# = Y1.GROUP#;

					SELECT SUBSTR(MEMBER,-6,2) INTO V_MEMBER FROM V$LOGFILE WHERE GROUP# = Y1.GROUP# AND MEMBER = V_MAX_MEMBER;

					DBMS_OUTPUT.PUT_LINE('  GROUP ' || Y1.GROUP# || ' (' );
					
						FOR Y IN (SELECT SUBSTR(MEMBER,-6,2) MEMBER2 FROM V$LOGFILE WHERE GROUP# = Y1.GROUP# AND MEMBER <> V_MAX_MEMBER) LOOP
							DBMS_OUTPUT.PUT_LINE('''' || V_DIRETORIO || 'redo' || Y1.GROUP# || '_' || Y.MEMBER2 || '.log'',' );
						END LOOP;
						
					DBMS_OUTPUT.PUT_LINE('''' || V_DIRETORIO || 'redo' || Y1.GROUP# || '_' || V_MEMBER || '.log''' );
					DBMS_OUTPUT.PUT_LINE(') SIZE '|| V_TAMANHO_REDO || 'M REUSE,');
			
			ELSE
			
				FOR Y IN (SELECT SUBSTR(MEMBER,-6,2) MEMBER2 FROM V$LOGFILE WHERE GROUP# = Y1.GROUP#) LOOP
					DBMS_OUTPUT.PUT_LINE('  GROUP ' || Y1.GROUP# || ' (''' || V_DIRETORIO || 'redo' || Y1.GROUP# || '_' || Y.MEMBER2 || '.log'') SIZE '|| V_TAMANHO_REDO || 'M REUSE,');
				END LOOP;
				
			END IF;
		END LOOP;
	   
	DBMS_OUTPUT.PUT_LINE(' ;}');

END;
/
